const quests=[
    {
        id: 0,
        nome: 'Qual é o nome completo do integrante RM?',
        alt1: 'Kim Seokjin',
        alt2: 'Kim Namjoon',
        alt3: 'Min Yoongi',
        alt4: 'Jung Hoseok',
        correct: 'Kim Namjoon',
    },
    {
        id: 1,
        nome: 'Em que ano o BTS debutou?',
        alt1: '2012',
        alt2: '2013',
        alt3: '2014',
        alt4: '2015',
        correct: '2013',
    },
    {
        id: 2,
        nome: 'Qual é o nome do fandom oficial do BTS?',
        alt1: 'Blink',
        alt2: 'EXO-L',
        alt3: 'ARMY',
        alt4: 'MOA',
        correct: 'ARMY',
    },
    {
        id: 3,
        nome: 'Qual foi a primeira música de trabalho do BTS?',
        alt1: 'Boy With Luv',
        alt2: 'No More Dream',
        alt3: 'Mic Drop',
        alt4: 'Fire',
        correct: 'No More Dream',
    },
    {
        id: 4,
        nome: 'Quem é conhecido como o "Golden Maknae" do grupo?',
        alt1: 'Jin',
        alt2: 'V',
        alt3: 'Jungkook',
        alt4: 'Jimin',
        correct: 'Jungkook',
    },
    {
        id: 5,
        nome: 'Qual membro do BTS nasceu em Busan?',
        alt1: 'Suga',
        alt2: 'Jungkook',
        alt3: 'Jimin',
        alt4: 'Ambos b e c',
        correct: 'Ambos b e c',
    },
    {
        id: 6,
        nome: 'Qual é o papel principal do Jin no grupo?',
        alt1: 'Dançarino principal',
        alt2: 'Vocalista',
        alt3: 'Rapper',
        alt4: 'Líder',
        correct: 'Vocalista',
    },
    {
        id: 7,
        nome: 'Como se chama a empresa que gerencia o BTS?',
        alt1: 'YG Entertainment',
        alt2: 'Big Hit Entertainment (atual HYBE)',
        alt3: 'SM Entertainment',
        alt4: 'JYP Entertainment',
        correct: 'Big Hit Entertainment (atual HYBE)',
    },
    {
        id: 8,
        nome: 'Qual foi o primeiro álbum completo do BTS?',
        alt1: 'Dark & Wild',
        alt2: 'Wings',
        alt3: 'Skool Luv Affair',
        alt4: 'Love Yourself: Tear',
        correct: 'Dark & Wild',
    },
    {
        id: 9,
        nome: 'Qual membro é conhecido por seu amor por máscaras e arte?',
        alt1: 'RM',
        alt2: 'J-Hope',
        alt3: 'V',
        alt4: 'Suga',
        correct: 'V',
    },
    {
        id: 10,
        nome: 'Em que ano o BTS ganhou o primeiro prêmio no MAMA (Mnet Asian Music Awards)?',
        alt1: '2013',
        alt2: '2014',
        alt3: '2015',
        alt4: '2016',
        correct: '2014',
    },
    {
        id: 11,
        nome: 'Qual é o nome do mixtape de Suga?',
        alt1: 'Agust D',
        alt2: 'Hope World',
        alt3: 'Mono',
        alt4: 'D-2',
        correct: 'Agust D',
    },
    {
        id: 12,
        nome: 'Quem é conhecido por suas habilidades em dança?',
        alt1: 'Jin',
        alt2: 'RM',
        alt3: 'J-Hope',
        alt4: 'Suga',
        correct: 'J-Hope',
    },
    {
        id: 13,
        nome: 'Qual membro do BTS costumava ser um atleta?',
        alt1: 'Jungkook ',
        alt2: 'Jimin',
        alt3: 'RM',
        alt4: 'Suga',
        correct: 'Jungkook ',
    },
    {
        id: 14,
        nome: 'Qual música do BTS bateu recordes no YouTube em 24 horas?',
        alt1: 'Dynamite',
        alt2: 'Butter',
        alt3: 'Boy With Luv',
        alt4: 'Todas as alternativas',
        correct: 'Todas as alternativas',
    },
    {
        id: 15,
        nome: 'Quem é o integrante mais velho do BTS?',
        alt1: 'Suga',
        alt2: 'Jin',
        alt3: 'RM',
        alt4: 'J-Hope',
        correct: 'Jin',
    },
    {
        id: 16,
        nome: 'Quantos integrantes fazem parte do BTS?',
        alt1: '5',
        alt2: '6',
        alt3: '7',
        alt4: '8',
        correct: '7',
    },
    {
        id: 17,
        nome: 'Qual álbum do BTS faz parte da série "Love Yourself"?',
        alt1: 'Wings',
        alt2: 'Map of the Soul: Persona',
        alt3: 'Love Yourself: Tear',
        alt4: 'BE',
        correct: 'Love Yourself: Tear',
    },
    {
        id: 18,
        nome: 'Qual membro do BTS adora cozinhar?',
        alt1: 'Jin',
        alt2: 'RM',
        alt3: 'J-Hope',
        alt4: 'V',
        correct: 'Jin',
    },
    {
        id: 19,
        nome: 'Em que ano o BTS se apresentou pela primeira vez no Billboard Music Awards?',
        alt1: '2015',
        alt2: '2016',
        alt3: '2017',
        alt4: '2018',
        correct: '2017',
    },
    {
        id: 20,
        nome: '',
        alt1: '',
        alt2: '',
        alt3: '',
        alt4: '',
        correct: '',
    },
]